Add top 10 security best practices for securing data in Amazon S3. Closes #1
turbot/steampipe-mod-aws-top10 pull request #2
Opened 2021-09-09 06:45 UTC by rajlearner17

2021-09-21 21:35 UTC, cbruno10 requested changes
@rajlearner17 Please see comments, thanks!

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/aws_top10.sp
> +benchmark "aws_top10" {
Do we need a top level benchmark? Similar to Thrifty, I think we'd be ok if people either use `steampipe check all`, or run per service, e.g., `steampipe check benchmark.s3`

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/docs/s3_top10.md
> +## Overview
Since we're in the top 10 mod, maybe this document should just be `s3.md`?

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/s3_top10.sp
> +  s3_top10_common_tags = merge(local.aws_top10_common_tags, {
```suggestion
  s3_common_tags = merge(local.top10_common_tags, {
```

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/aws_top10.sp
> +  aws_top10_common_tags = {
```suggestion
  top10_common_tags = {
```

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/aws_top10.sp
> +    aws_top10 = "true"
How would a user use this tag in the UI, i.e., what would they be looking for/filtering for?

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/s3_top10.sp
> +    s3_top10 = "true"
```suggestion
    service = "s3"
```

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/s3_top10.sp
> +    s3_top10 = "true"
I think this is a bit different than the compliance mods - the services are the top level separators in this mod, so we can simplify the tags to call out per service and not include the words "top10" at all (since the mod name already includes it)

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/s3_top10.sp
> +benchmark "s3_top10" {
```suggestion
benchmark "s3" {
```

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/s3_top10.sp
> +  documentation = file("./aws_top10/docs/s3_top10.md")
```suggestion
  documentation = file("./aws_top10/docs/s3.md")
```

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/aws_top10.sp
> +locals {
Do we need a directory called `aws_top10`? I don't think we'll have other benchmarks in this mod, so we could go with a folder `controls` (like in Thrifty mods) and then call this file `top10.sp`

2021-09-21 21:35 UTC, cbruno10 commented on mod.sp
> +  categories    = ["aws", "top10", "compliance", "public cloud", "security"]
```suggestion
  categories    = ["aws", "compliance", "public cloud", "security"]
```

I don't think we have, or will add, a top10 category. If we do in the future, we can always add this back

2021-09-21 21:35 UTC, cbruno10 commented on aws_top10/s3_top10.sp
> +  sql           = query.s3_bucket_public_access_block_account.sql
Are we re-using these queries across services at all, or do you think queries will generally only be used for a specific control?

2021-09-21 21:35 UTC, cbruno10 commented on README.md
> +# AWS Top 10 Best Practices For Most Used Services
Do we need `For Most Used Services`? Is our posturing that this is a mod for best security practices, or are we keeping it more general for now?

2021-09-22 09:43 UTC, rajlearner17 commented on aws_top10/aws_top10.sp
> +benchmark "aws_top10" {
ok, sounds good. Earlier I was planning to stack under top-10, but it makes sense to follow a similar pattern like thrifty.

2021-09-22 09:48 UTC, rajlearner17 commented on aws_top10/s3_top10.sp
> +    s3_top10 = "true"
Agreed

2021-09-22 09:54 UTC, rajlearner17 commented on aws_top10/s3_top10.sp
> +  sql           = query.s3_bucket_public_access_block_account.sql
There are small changes in the queries, I guess we are not reusing this here for top10 as it's not a compliance mod. So we can treat these as thrifty queries.

2021-09-22 09:56 UTC, rajlearner17 commented on README.md
> +# AWS Top 10 Best Practices For Most Used Services
For the time being, we are keeping it more general now to see how we get a response around it.

2021-09-22 10:27 UTC, rajlearner17 commented on aws_top10/aws_top10.sp
> +    aws_top10 = "true"
In the hub we just show the tags and allow you to do some searching of mods/controls/benchmarks with similar tags

2021-09-22 10:30 UTC, rajlearner17 commented on aws_top10/aws_top10.sp
> +    aws_top10 = "true"
Keeping it as below may help?
```
locals {
  top10_common_tags = {
    plugin    = "aws"
    top10   = "true"
  }
}
```

2023-05-16 18:09 UTC, cbruno10 commented
Closing PR for now, as we've paused work on this mod. Can re-open when ready to review.

2023-05-16 18:09 UTC, closed without merging